### ISSUE TITLE
Evaluation inputs

### ISSUE THREAD

**Issue by nancyide** [lapps/org.lappsgrid.all#10]
Allow more than 2 inputs to OAQA

**Comment by Digo** [comment]
Hi @nancyide, what do you mean by "inputs"? 

The oaqa evaluation component should accept both gold and test's data/AnnotationType/Feature.

**Comment by nancyide** [comment]
Currently can take only the gold data and one test data set. Would like to feed multiple  test data sets into OAQA so we don't have to instantiate one per test set.

**Comment by Digo** [comment]
1) Evaluation component is single web service, instantiating multiple evaluation clients would not cost extra resource. 
2) Since each pair of gold/test data correspond to one set of evaluation metrics. Supporting multiple test data set means generating multiple sets of reports for each test sets, which might confuse the user?

**Comment by ksuderman** [comment]
This issue was moved to lapps/lapps.github.io#20
